config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "home/index"
  get "home/profile"
  patch "home/update_profile"
  resources :galleries do
    post "generate_image", on: :member
    post "generate_image_variation", on: :member
    get "generate_random_prompt", on: :member
  end
  resources :templates
  resources :groups do
    post "create_word", on: :member
    resources :word_groups
  end
  resources :docs do
    post "mark_current", on: :member
    post "create_variation", on: :member
  end
  post "groups/:id/select_word/:word_id", to: "groups#select_word", as: :select_group_word
  post "groups/:id/select_words", to: "groups#select_words", as: :select_group_words

  resources :words do
    post "speak", on: :member
    post "generate_image", on: :member
    post "generate_image_variation", on: :member
  end
  resources :categories
  resources :posts
  resources :docs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/word_group.rb
# == Schema Information
#
# Table name: word_groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer          not null
#  word_id    :integer          not null
#
# Indexes
#
#  index_word_groups_on_group_id  (group_id)
#  index_word_groups_on_word_id   (word_id)
#
# Foreign Keys
#
#  group_id  (group_id => groups.id)
#  word_id   (word_id => words.id)
#
class WordGroup < ApplicationRecord
  belongs_to :word
  belongs_to :group
  # belongs_to :user, optional: true
end

app/controllers/word_groups_controller.rb
class WordGroupsController < ApplicationController
  before_action :set_word_group, only: %i[ show edit update destroy ]

  # GET /word_groups or /word_groups.json
  def index
    @group = Group.find(params[:group_id])
    @word_groups = @group.word_groups.all
  end

  # GET /word_groups/1 or /word_groups/1.json
  def show
  end

  # GET /word_groups/new
  def new
    @group = Group.find(params[:group_id])

    @words = Word.take(10)
    @word_group = @group.word_groups.new
    @word = Word.new
  end

  # GET /word_groups/1/edit
  def edit
  end

  # POST /word_groups or /word_groups.json
  def create
    @word_group = WordGroup.new(word_group_params)

    respond_to do |format|
      if @word_group.save
        format.html { redirect_to word_group_url(@word_group), notice: "Word group was successfully created." }
        format.json { render :show, status: :created, location: @word_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /word_groups/1 or /word_groups/1.json
  def update
    respond_to do |format|
      if @word_group.update(word_group_params)
        format.html { redirect_to word_group_url(@word_group), notice: "Word group was successfully updated." }
        format.json { render :show, status: :ok, location: @word_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /word_groups/1 or /word_groups/1.json
  def destroy
    @word_group.destroy!

    respond_to do |format|
      format.html { redirect_to word_groups_url, notice: "Word group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_word_group
    @group = Group.find(params[:group_id])
    @word_group = WordGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def word_group_params
    params.require(:word_group).permit(:group_id, :user_id, :word_id)
  end
end

app/helpers/word_groups_helper.rb
module WordGroupsHelper
end

app/views/word_groups/_form.html.erb
<% form_for @word_group, url: new_group_word_group_path(@group.id) do |f| %>
  <% f.simple_fields_for :word do |word_form| %>%
    # Here you have all simple_form methods available
    <%= word_form.input :name %>
  <% end %>
<% end %>

app/views/word_groups/_word_group.html.erb
<div id="<%= dom_id word_group %>">
  <p>
    <strong>Word:</strong>
    <%= word_group.word.name %>
  </p>
  <p>
    <strong>Group:</strong>
    <%= word_group.group_id %>
  </p>
</div>

app/views/word_groups/edit.html.erb
<h1>Editing word group</h1>
<%= render "form", word_group: @word_group %>
<br>
<div>
  <%= link_to "Show this word group", @word_group %> |
  <%= link_to "Back to word groups", group_word_groups_path(@group) %>
</div>

app/views/word_groups/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Word groups</h1>
<div id="word_groups">
  <% @groups.each do |group| %>
    <% group.word_groups.each do |word_group| %>
      <%= word_group.word %>
      <p>
        <%= link_to word_group.word, group_word_group_path(group, word_group) %>
      </p>
    <% end %>
  <% end %>
</div>
<%= link_to "New word group", new_word_group_path %>

app/views/word_groups/new.html.erb
<h1>New word group</h1>
<%= render "form", word_group: @word_group %>
<br>
<% if @words %>
  <% @words.each do |word| %>
    <%= word.id %>: <%= word.name %>
  <% end %>
<% end %>
<div>
  <%= link_to "Back to word groups", group_word_groups_path(@group) %>
</div>

app/views/word_groups/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @word_group %>
<div>
  <%= link_to "Edit this word group", edit_word_group_path(@word_group) %> |
  <%= link_to "Back to word groups", group_word_groups_path(@group) %>
  <%= button_to "Destroy this word group", @word_group, method: :delete %>
</div>