config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "home/index"
  get "home/profile"
  patch "home/update_profile"
  resources :galleries do
    post "generate_image", on: :member
    post "generate_image_variation", on: :member
    get "generate_random_prompt", on: :member
  end
  resources :templates
  resources :groups do
    post "create_word", on: :member
    resources :word_groups
  end
  resources :docs do
    post "mark_current", on: :member
    post "create_variation", on: :member
  end
  post "groups/:id/select_word/:word_id", to: "groups#select_word", as: :select_group_word
  post "groups/:id/select_words", to: "groups#select_words", as: :select_group_words

  resources :words do
    post "speak", on: :member
    post "generate_image", on: :member
    post "generate_image_variation", on: :member
  end
  resources :categories
  resources :posts
  resources :docs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/templates/_form.html.erb
<%= simple_form_for(@template) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :name %>
    <%= f.input :template_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/templates/_template.html.erb
<div id="<%= dom_id template %>">
  <p>
    <strong>User:</strong>
    <%= template.user_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= template.name %>
  </p>

  <p>
    <strong>Template type:</strong>
    <%= template.template_type %>
  </p>

</div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render "form", template: @template %>

<br>

<div>
  <%= link_to "Show this template", @template %> |
  <%= link_to "Back to templates", templates_path %>
</div>

app/views/templates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Templates</h1>

<div id="templates">
  <% @templates.each do |template| %>
    <%= render template %>
    <p>
      <%= link_to "Show this template", template %>
    </p>
  <% end %>
</div>

<%= link_to "New template", new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render "form", template: @template %>

<br>

<div>
  <%= link_to "Back to templates", templates_path %>
</div>

app/views/templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @template %>

<div>
  <%= link_to "Edit this template", edit_template_path(@template) %> |
  <%= link_to "Back to templates", templates_path %>

  <%= button_to "Destroy this template", @template, method: :delete %>
</div>