config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "home/index"
  get "home/profile"
  patch "home/update_profile"
  resources :galleries do
    post "generate_image", on: :member
    post "generate_image_variation", on: :member
    get "generate_random_prompt", on: :member
  end
  resources :templates
  resources :groups do
    post "create_word", on: :member
    resources :word_groups
  end
  resources :docs do
    post "mark_current", on: :member
    post "create_variation", on: :member
  end
  post "groups/:id/select_word/:word_id", to: "groups#select_word", as: :select_group_word
  post "groups/:id/select_words", to: "groups#select_words", as: :select_group_words

  resources :words do
    post "speak", on: :member
    post "generate_image", on: :member
    post "generate_image_variation", on: :member
  end
  resources :categories
  resources :posts
  resources :docs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :words

  def print_words
    words.map(&:name)
  end

  def self.uncategorized_id
    7
  end
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Group < ApplicationRecord
  belongs_to :user
  default_scope { includes(:word_groups) }

  has_many :word_groups
  has_many :words, -> { distinct }, through: :word_groups
  has_many :categories, -> { distinct }, through: :words
  accepts_nested_attributes_for :words, reject_if: blank?, allow_destroy: false
  accepts_nested_attributes_for :word_groups, allow_destroy: true

  def remaining_words(words_to_filter = nil)
    words_to_filter ||= Word.all
    words_to_filter.where.not(id: word_ids)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy create_word select_words ]

  # GET /groups or /groups.json
  def index
    puts "@current_user:#{@current_user.class} #{@current_user.inspect}"
    @groups = @current_user.groups.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @words = @group.words
    @word = @group.words.new
  end

  def create_word
    puts "", "CREATE: "
    puts "PARAMS: #{params}"
    word_params = params["word"]
    puts "", "word_params:", word_params

    @word = Word.find(name: word_params["name"])
    unless @word
      @word = Word.find_or_create_by(name: word_params["name"], category_id: Category.uncategorized_id)
    end
    word_group = WordGroup.new(group_id: @group.id, word_id: @word.id)
    # @group.word_ids << @word.id

    respond_to do |format|
      if word_group.save
        format.html { redirect_to group_url(@group), notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def select_words
    puts "PARAMS: #{params}"
    wors_list = params["group"]["word_ids"]
    # puts "wors_list: #{wors_list.compact_blank}"
    # @group.attributes = { "word_ids" => [] }.merge(params[:group] || {})
    @group.word_ids = wors_list
    # @word = Word.find(params["word_id"])
    # @word.speak
    # @group.word_groups.find_or_create_by!(word_id: @word.id)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group) }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def select_word
    puts "PARAMS: #{params}"
    pp params
    @word = Word.find(params["word_id"])
    @word.speak
    @group.word_groups.find_or_create_by!(word_id: @word.id)

    # respond_to do |format|
    #   if @group.save
    #     format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
    #     format.json { render :show, status: :created, location: @group }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @group.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @words = Word.last(5)
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = @current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.includes(:words, :word_groups).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, word_ids: [])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # def display_main_image(main_image, size = "500")
  #   image_tag main_image, class: "word-display"
  # end

  # def speech_button(word)
  #   button_to icon("fa-regular", "comment-dots"), speak_word_path(word), class: "btn", method: :post
  # end

  # def word_link(group, word)
  #   link_to(select_group_word_path(group.id, word.id), data: { turbo_method: :post }) do
  #     if word.main_image
  #       display_main_image(word.main_image)
  #     else
  #       speech_button(word)
  #     end
  #   end
  # end
end

app/views/groups/_create_word.html.erb
<%= simple_form_for @word, url: "/groups/#{group.id}/create_word", method: :post do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Save' %>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

</div>

app/views/groups/_select_word.html.erb
<%= simple_form_for :word_group, url: "/groups/#{group_id}/select_words", method: :post do |form| %>
  <div class="col-md-12">
    <div class="clearfix">
      <div class="btn-group-vertical float-start" role="group" aria-label="Vertical button group">
        <%= f.association :word %>
      </div>
    </div>
    <%= form.submit "SAVE", id: "save-btn", class: "btn btn-success" %>
  </div>
<% end %>

app/views/groups/_select_words.html.erb
<div data-controller="select_words">
  <%= simple_form_for :group, url: "/groups/#{group.id}/select_words", method: :post do |form| %>
    <div class="d-grid gap-2">
      <%= form.submit "SAVE", id: "save-btn", class: "btn btn-success btn-lg" %>
    </div>
    <div class="word-wrapper">
      <% words.each do |word| -%>
        <div class="word-container">
          <%= check_box_tag :word_ids, word.id, group.words.include?(word), :name => 'group[word_ids][]' -%>
          <%= label_tag :word_ids, word.name -%>
          <%= word_image_link(word) %>
        </div>
      <% end -%>
    </div>
  <% end %>
</div>

app/views/groups/_table.html.erb
<table class="table table-bordered table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Group</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= group.id %></td>
        <td><%= group.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_word_fields.html.erb
<div class='nested-fields'>
  <%= f.input :name, :hint => 'how should it be tagged' %>
  <%= link_to_remove_association "remove word", f %>
</div>

app/views/groups/_word_group_fields.html.erb
<div class='nested-fields'>
  <%= link_to_add_association 'or create a new word', f, :word, class: 'add-word' %>
  <%= link_to_remove_association f,class: 'remove-tag btn btn-default btn-xs' do %>
    <span class="glyphicon glyphicon-remove"></span>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>
<div class="word-select">
  <%= render 'select_words', words: @words, group: @group %>
</div>
<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      <%= link_to "Show this group", group %>
    </p>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<%= link_to "Edit this group", edit_group_path(@group) %>
<div class='row'>
  <div class='col'>
    <%= render 'create_word', group: @group %>
  </div>
  <div class='col' id="words">
    <% @words.each do |word| %>
      <p><%= word.name %></p>
    <% end %>
  </div>
</div>